# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01b_boson.ipynb.

# %% auto 0
__all__ = ['Boson']

# %% ../nbs/01b_boson.ipynb 3
from .elementary_particle import ElementaryParticle

# %% ../nbs/01b_boson.ipynb 5
class Boson(ElementaryParticle):
    pass
