# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_conservation.ipynb.

# %% auto 0
__all__ = ['Conservation', 'Spin']

# %% ../nbs/03_conservation.ipynb 3
from .core import *

# %% ../nbs/03_conservation.ipynb 5
class Conservation:
    pass

# %% ../nbs/03_conservation.ipynb 7
class Spin(Conservation):
    pass
    # so when two particles interact, the spin is conserve!
