# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_elementary_particle.ipynb.

# %% auto 0
__all__ = ['ElementaryParticle']

# %% ../nbs/01_elementary_particle.ipynb 9
class ElementaryParticle:
    
    # every particle is either a fermion or a boson 
    PARTICLE_CLASSIFICATION = ("fermion", "boson")
    
    def __init__(self):
        pass
