# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01a_fermion.ipynb.

# %% auto 0
__all__ = ['Fermion']

# %% ../nbs/01a_fermion.ipynb 3
from .elementary_particle import ElementaryParticle

# %% ../nbs/01a_fermion.ipynb 4
class Fermion(ElementaryParticle):
    
    FERMION_CLASSIFICATION = ("electron", "up_quark", "down_quark", "electron_neutrino")
    pass
