# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_force.ipynb.

# %% auto 0
__all__ = ['Force', 'ElectromagneticForce']

# %% ../nbs/02_force.ipynb 4
class Force:
    FORCE_CLASSIFICATION = ("elelectromagnetic", "strong", "weak", "gravity")
    pass

# %% ../nbs/02_force.ipynb 6
class ElectromagneticForce(Force):
    pass
