# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_particle.ipynb.

# %% auto 0
__all__ = ['Particle', 'Fermion', 'Lepton', 'Quark', 'Boson', 'GaugeBoson', 'ScalarBoson', 'HiggsBoson', 'WaveFunction']

# %% ../nbs/01_particle.ipynb 9
class Particle:
    
    # every particle is either a fermion or a boson 
    PARTICLE_CLASSIFICATION = ("fermion", "boson")
    
    def __init__(self):
        pass

# %% ../nbs/01_particle.ipynb 12
class Fermion(Particle):
    
    #FERMION_CLASSIFICATION = ("electron", "up_quark", "down_quark", "electron_neutrino")
    SPIN = 1/2
    pass

# %% ../nbs/01_particle.ipynb 14
class Lepton(Fermion):
    
    LEPTON_CLASSIFICATION = (
        "electron", "muon", "tau",
        "electron_neutrino", "muon_neutrino", "tau_neutrono")
    
    pass

# %% ../nbs/01_particle.ipynb 15
class Quark(Fermion):
    
    QUARK_CLASSIFICATION = (
        "up", "charm", "top",
        "down", "strange", "bottom")
    
    pass

# %% ../nbs/01_particle.ipynb 18
class Boson(Particle):
    BOSON_CLASSIFICATION = ()
    pass

# %% ../nbs/01_particle.ipynb 19
class GaugeBoson(Boson):
    
    GAUGE_BOSON_CLASSIFICATION = ("gluon", "photon", "z_boson", "w_boson")
    SPIN = 1
    
    def spin(self):
        return SPIN

# %% ../nbs/01_particle.ipynb 20
class ScalarBoson(Boson):
    
    SCALAR_BOSON_CLASSIFICATION = ("higgs_boson")
    SPIN = 0

    def __init__(self, name): # the name of the particle
        if name not in SCALAR_BOSON_CLASSIFICATION:
            raise ValueError("This particle isn't a part of Bosons")
        else:
            self.name = name
        
    def spin(self):
        """Return the spin"""
        return SPIN

# %% ../nbs/01_particle.ipynb 21
class HiggsBoson(ScalarBoson):
    pass

# %% ../nbs/01_particle.ipynb 22
class WaveFunction:
    def behave(self):
        # based on the spin of the particle
        pass
